######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 27 19:50:23 2009
######################################################################

TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS = 	revfe \
		plugins
