######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 22 12:29:04 2008
######################################################################

TEMPLATE = lib
TARGET = RevNaviPlugin
DEPENDPATH += .
INCLUDEPATH += . ../../revfe /home/michael/libosmscout/libosmscout/include /home/michael/libosmscout/libosmscout-map-qt/include /home/michael/libosmscout/libosmscout-map/include
CONFIG += plugin debug
LIBS += -L/home/michael/libosmscout/libosmscout/src/.libs -L/home/michael/libosmscout/libosmscout-map/src/.libs -L/home/michael/libosmscout/libosmscout/src/.libs -L/home/michael/libosmscout/libosmscout-map-qt/src/.libs -L/home/michael/libosmscout/libosmscout-map/src/.libs -L/home/michael/libosmscout/libosmscout/src/.libs -losmscout -losmscoutmap -losmscoutmapqt

win32:DESTDIR = ../../revfe/plugins/
unix:DESTDIR = ../../revfe/plugins/
QT += declarative
CONFIG += embed_manifest_exe
# Input
HEADERS += revnavi.h ../../revfe/baseinterface.h \
    mapview.h
SOURCES += revnavi.cpp ../../revfe/ipcmessage.cpp \
    mapview.cpp
unix:target.path = /usr/share/revfe/plugins/
unix:INSTALLS += target
