Document: revfe
Title: Debian revfe Manual
Author: <insert document author here>
Abstract: This manual describes what revfe is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/revfe/revfe.sgml.gz

Format: postscript
Files: /usr/share/doc/revfe/revfe.ps.gz

Format: text
Files: /usr/share/doc/revfe/revfe.text.gz

Format: HTML
Index: /usr/share/doc/revfe/html/index.html
Files: /usr/share/doc/revfe/html/*.html
